### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Slasar41** [Inareous/Minimal-CS-Manga-Reader#13] opened 2020-07-08 20:55 UTC
Could you implement this feature?
- Make the images to be able to grab and move horizontally like in DDS Manga Reader, currently it's only move vertically. Also move the images with left and right arrow key.
- Able to scroll through the chapter list without clicking it, like this:
![DwAZVA7qu7](https://user-images.githubusercontent.com/28888646/86968363-4380ef80-c196-11ea-847d-e2e03f0e72a9.gif)
- A bookmark system. I often let the chapters to pile up so I can read it in one go. But sometime I forgot until which chapter I read it last time.

Also I've found a bug, I can't input the page number manually.
![image](https://user-images.githubusercontent.com/28888646/86968477-6f03da00-c196-11ea-869a-def1fcd4ba6c.png)

**Comment by Inareous** [comment] 2020-07-08 22:07
1. Related to #8. I think a separate issue to keep track of interest will be good.
2. Looks good to be implemented, i'm worried about scrolling too far at once though.
3. This one is rather tricky, a rough implementation of this can be made but i'm not sure how I'm gonna go forward smoothing the feature, for now let's track this on separate issue.
4. On first design iteration, this used to be intentional actually. Not sure how good it would be to navigate pages using image numbers, #7 would be a cleaner solution.

**Comment by Slasar41** [comment] 2020-07-09 18:06
Thanks for creating separate feature request.

For inputing the page number manually, it's useful when you have a folder contains 200 more images, usually downloaded from H-Sites.
I'd rather input the page number rather than scrolling through the images to reach a certain part.
Also that page number field has an underline so it act as if can be inputed manually like on margin, scroll, and zoom field.

**Comment by Inareous** [comment] 2020-07-10 22:34
Implemented on v0.1.0.8 release.

**Comment by Slasar41** [comment] 2020-07-11 15:18
Nice, thanks.

**Comment by Inareous** [comment] 2020-07-12 05:18
Closing this one.

Feel free to comment here if point 2 and 4 is not working as intended.

**Closed as completed by Inareous** 2020-07-12 05:18 UTC
