### ISSUE TITLE
Can't read archived chapters

### ISSUE THREAD

**Issue by GenoXu** [Inareous/Minimal-CS-Manga-Reader#12] opened 2020-07-07 19:40 UTC

**Comment by Inareous** [comment] 2020-07-07 23:26
This is due to my old self's stupidity of appending "-path=" to arguments and only accepting that as input instead of handling arguments path normally.
This should be easy to fix, i think.

**Comment by Inareous** [comment] 2020-07-08 00:41
Try v0.1.0.7 release

As for FMD, the recommended way would be to change `Options->General->Parameters:` to be `"%PATH%"` instead of the default value, this way MCS grab all chapter and you can navigate between chapter.

**Comment by GenoXu** [comment] 2020-07-08 08:18
@Inareous Now It works with FMD and when navigating to the folder of the archived chapter, but still no luck when opening directly (I've installed NET Core 3.1 Desktop Runtime)

**Comment by Inareous** [comment] 2020-07-08 11:42
Hmm, thats weird. Can you provide a gif example? Something like below:
![zip](https://user-images.githubusercontent.com/18087264/86914358-6ab1cf80-c14a-11ea-9665-083d86bf527c.gif)

**Comment by GenoXu** [comment] 2020-07-08 16:48
![MCS6](https://user-images.githubusercontent.com/31614025/86946928-fcb5da00-c142-11ea-8eb4-cf3a3319547b.gif)

**Comment by Inareous** [comment] 2020-07-08 20:31
So, after a couple tries i've managed to reproduce the issue but i'm not sure how to fix it.

Steps i did to reproduce :

1. Remove all releases of MCS folder (everywhere).
2. Get v0.1.0.6 release or below, then extract it.
3. Try "open with .." to MCS.exe, it will fail to load images.
4. Get latest release, then extract it. (Don't delete the previous release extracted folder)
5. Try "open with .." to latest MCS.exe, it will fail to load images.

A simple solution i've found is just to remove previous releases of MCS folder. To be safe, maybe remove all releases of MCS and just extract the latest one (try using different directory name/location).
My first thought on this is that "open with" windows will point to the older version if its still exist, even though we point it to the newer version, maybe because the filename is same?

**Comment by GenoXu** [comment] 2020-07-08 21:20
I Just tried out your suggestion and It worked (I even used the same directory as before). 
Indeed, I think It has something to do with "open with" window pointing to the older version
 instead of the newer one just like you said (you may want to point out all this under [Features](https://github.com/Inareous/Minimal-CS-Manga-Reader#features)).
Anyway, Thanks a lot!

**Comment by Inareous** [comment] 2020-07-08 22:38
Glad it worked out.

Yeah, adding native context or file association to archive file may be something to consider if this happens often, we'll see.

Closing this for now.

**Closed as completed by Inareous** 2020-07-08 22:38 UTC
